require: standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1.3
  SuggestExtensions: false
Lint/OrAssignmentToConstant:
  Enabled: false
Security/Eval:
  Enabled: false
