require "spec_helper"

RSpec.describe "Day 7: Laboratories" do
  let(:runner) { Runner.new("2025/07") }
  let(:input) do
    <<~TXT
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
    TXT
  end

  describe "Part One" do
    let(:solution) { runner.execute!(input, part: 1) }

    it "calculates the number of times the beam splits" do
      expect(solution).to eq(21)
    end
  end

  describe "Part Two" do
    let(:solution) { runner.execute!(input, part: 2) }

    it "calculates the number of timelines after quantum splitting" do
      expect(solution).to eq(40)
    end
  end
end
